export enum ErrorCodes {
  // Generic HTTP Status-based Errors
  VALIDATION_ERROR = "VALIDATION_ERROR",
  AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",
  AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR",
  NOT_FOUND_ERROR = "NOT_FOUND_ERROR",
  CONFLICT_ERROR = "CONFLICT_ERROR",
  SERVER_ERROR = "SERVER_ERROR",

  // Specific Validation Errors (when more detail is needed)
  EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_USER_ID_FORMAT = "INVALID_USER_ID_FORMAT",
  PASSWORD_TOO_WEAK = "PASSWORD_TOO_WEAK",
  INVALID_EMAIL_FORMAT = "INVALID_EMAIL_FORMAT",

  // Specific Resource-Related Errors
  USER_NOT_FOUND = "USER_NOT_FOUND",
  BUDGET_NOT_FOUND = "BUDGET_NOT_FOUND",
  INVOICE_NOT_FOUND = "INVOICE_NOT_FOUND",

  // Specific Operation-Related Errors
  PASSWORD_RESET_FAILED = "PASSWORD_RESET_FAILED",
  USER_DELETION_FAILED = "USER_DELETION_FAILED",
}
